blueprint:
  name: Ventilate Room
  description: Reminds you to close window after ventilating and controls cover
  domain: automation
  input:
    window_sensor:
      name: Window Sensor
      description: Window sensor to trigger the automation.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    cover:
      name: Cover
      description: Cover to control
      selector:
        entity:
          domain: cover
          device_class: shutter
    ventilation_time:
      name: Ventilation Time
      description: Time to wait after window is opened
      default: 20
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: "min"
    elevation:
      name: Sun Elevation
      description: Below this elevation the cover will close automatically
      default: -5
      selector:
        number:
          min: -30
          max: 20
          unit_of_measurement: "°"
          mode: slider
    media_players:
      name: Media Players
      description: Media Players to announce when its time to close the windows. Comma seperated list is possible
    tts_script:
      name: TTS Script
      description: The script that should be used for tts
      default: script.sonos_say
      selector:
        target:
          entity:
            domain: script
    text:
      name: Text
      description: Text to announce when its time to close the windows
      selector:
        text:
    text_timeout:
      name: Timeout Text
      description: Text to announce when window is open way to long
      selector:
        text:

trigger:
  - platform: state
    entity_id: !input window_sensor

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input window_sensor
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input cover
                    state: "0"
                    attribute: current_position
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input cover
          - delay:
              minutes: !input ventilation_time
          - condition: state
            entity_id: !input window_sensor
            state: "on"
          - service: notify.notify
            data:
              message: !input text
          - service: script.turn_on
            target: !input tts_script
            data:
              variables:
                where: !input media_players
                what: !input text
          - delay:
              minutes: !input ventilation_time
          - service: notify.notify
            data:
              message: !input text_timeout
          - service: script.turn_on
            target: !input tts_script
            data:
              variables:
                where: !input media_players
                what: !input text_timeout
      - conditions:
          - condition: state
            entity_id: !input window_sensor
            state: "off"
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input elevation
        sequence:
          - service: cover.close_cover
            target:
              entity_id: !input cover
    default: []
mode: restart
